


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://docker-integration:5432/ar
    username: mcadmin
    password: mcadmin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
server:
  port: 8888
